### PR TITLE
Allow countries versions 3.X or 4.X

### PR DESCRIPTION
**Pull request by niels**
[There don't seem to be any breaking changes in v4.](https://github.com/countries/countries/blob/master/CHANGELOG.md#400-20210611-0947-0100)

### CODE REVIEW

**Comment by henrik** [comment]
Any updates, please?

This gem is currently the one thing preventing us from updating `countries` to 5 (so the next mayor) – that one does have [some breaking changes](https://github.com/countries/countries/blob/master/CHANGELOG.md#500-20220403-1744-0000). It would be more motivating to look into those if this was merged first.

**Comment by niels** [comment]
Technically, [`facebookbusiness` still supports Ruby 2.5 & 2.6](https://github.com/facebook/facebook-ruby-business-sdk/blob/ef51980bf9ed181e69c7e79903518f11be7bce81/facebookbusiness.gemspec#L35).

So with [`countries` v5.0.0. dropping support for those Ruby versions](https://github.com/countries/countries/blob/9046bc79298986554f01ce6363c9310b1081a8f4/CHANGELOG.md#500-20220403-1744-0000), it would be incompatible with `facebookbusiness`.

(It would, of course, still be great to at least get this PR merged so that `countries` v4 gets allowed.)

**Comment by henrik** [comment]
@niels Good point. I've now [made a PR](https://github.com/facebook/facebook-ruby-business-sdk/pull/180) for supporting countries 5 and only requiring Ruby 2.7. We can then use that fork in our app until/if Facebook want to merge.

**Comment by alanho** [comment]
hi, this issue is fixed in the 56588d4e4d02d1b1e9856a8de41b1670ca1ec8ed commit. so closing it for now

**Pull request closed without merging**
